// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjbRHpis8vjOSMCmITY1gVjPkaWEkl5Lk',
    appId: '1:561381085606:web:24e5dccadc8176a4a6ff67',
    messagingSenderId: '561381085606',
    projectId: 'math-adventure-e52a4',
    authDomain: 'math-adventure-e52a4.firebaseapp.com',
    storageBucket: 'math-adventure-e52a4.firebasestorage.app',
    measurementId: 'G-Q1821SYK8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjP0kPRC8ALz5ikEXfAHTHNwW9PwnIvpU',
    appId: '1:561381085606:android:46feaaf525b6f953a6ff67',
    messagingSenderId: '561381085606',
    projectId: 'math-adventure-e52a4',
    storageBucket: 'math-adventure-e52a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIo2vf6HC8ewYY2qFRVz_QG26f_TyVUes',
    appId: '1:561381085606:ios:f8d4884881c546d4a6ff67',
    messagingSenderId: '561381085606',
    projectId: 'math-adventure-e52a4',
    storageBucket: 'math-adventure-e52a4.firebasestorage.app',
    iosBundleId: 'com.mathAdventure',
  );
}
